# Usamos una imagen oficial y ligera de Python
FROM python:3.11-slim

# Le decimos a Docker en qué carpeta trabajar adentro del contenedor
WORKDIR /Backend

# Copiamos las dependencias y las instalamos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el resto de tu código (main.py)
COPY . .

# Exponemos el puerto de FastAPI
EXPOSE 8000

# Comando para encender el servidor con recarga automática
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]