{
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Estado de la Web (Laravel)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://web:80\"}"
    }
   ]
  },
  {
   "title": "Salud del Balanceador (Nginx)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://nginx:80\"}"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta (Latencia)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}