global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.log'

receivers:
- name: 'web.log'
  # Configuración básica para ver las alertas en el log del contenedor
  # Aquí es donde se agregaría Discord/Telegram/Email en el futuro
